// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: v1/StateManager/communication.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace me.jordanwood.proto.v1.statemanager {
  public static partial class State
  {
    static readonly string __ServiceName = "v1.proto.statemanager.State";

    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest> __Marshaller_v1_proto_statemanager_InitialConnectionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> __Marshaller_v1_proto_statemanager_ConnectionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.ConnectionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.PackedState> __Marshaller_v1_proto_statemanager_PackedState = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.PackedState.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.EntityEditRequest> __Marshaller_v1_proto_statemanager_EntityEditRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.EntityEditRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.GenericResponse> __Marshaller_v1_proto_statemanager_GenericResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.GenericResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.EntityRequest> __Marshaller_v1_proto_statemanager_EntityRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.EntityRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.AuthorityResponse> __Marshaller_v1_proto_statemanager_AuthorityResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.AuthorityResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::me.jordanwood.proto.v1.statemanager.EntityState> __Marshaller_v1_proto_statemanager_EntityState = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::me.jordanwood.proto.v1.statemanager.EntityState.Parser.ParseFrom);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest, global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> __Method_Connect = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest, global::me.jordanwood.proto.v1.statemanager.ConnectionRequest>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Connect",
        __Marshaller_v1_proto_statemanager_InitialConnectionRequest,
        __Marshaller_v1_proto_statemanager_ConnectionRequest);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.PackedState> __Method_FullLoad = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.PackedState>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FullLoad",
        __Marshaller_v1_proto_statemanager_ConnectionRequest,
        __Marshaller_v1_proto_statemanager_PackedState);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityEditRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse> __Method_UpdateObject = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityEditRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateObject",
        __Marshaller_v1_proto_statemanager_EntityEditRequest,
        __Marshaller_v1_proto_statemanager_GenericResponse);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityEditRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse> __Method_CreateObject = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityEditRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateObject",
        __Marshaller_v1_proto_statemanager_EntityEditRequest,
        __Marshaller_v1_proto_statemanager_GenericResponse);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse> __Method_RemoveObject = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RemoveObject",
        __Marshaller_v1_proto_statemanager_EntityRequest,
        __Marshaller_v1_proto_statemanager_GenericResponse);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.AuthorityResponse> __Method_RetrieveAuthority = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.AuthorityResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RetrieveAuthority",
        __Marshaller_v1_proto_statemanager_EntityRequest,
        __Marshaller_v1_proto_statemanager_AuthorityResponse);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.EntityState> __Method_RetrieveState = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.EntityState>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RetrieveState",
        __Marshaller_v1_proto_statemanager_EntityRequest,
        __Marshaller_v1_proto_statemanager_EntityState);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.EntityState> __Method_StateStream = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.EntityState>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StateStream",
        __Marshaller_v1_proto_statemanager_ConnectionRequest,
        __Marshaller_v1_proto_statemanager_EntityState);

    static readonly grpc::Method<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> __Method_SubscriptionStream = new grpc::Method<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.ConnectionRequest>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscriptionStream",
        __Marshaller_v1_proto_statemanager_ConnectionRequest,
        __Marshaller_v1_proto_statemanager_ConnectionRequest);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::me.jordanwood.proto.v1.statemanager.CommunicationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of State</summary>
    public abstract partial class StateBase
    {
      public virtual global::System.Threading.Tasks.Task<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> Connect(global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::me.jordanwood.proto.v1.statemanager.PackedState> FullLoad(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::me.jordanwood.proto.v1.statemanager.GenericResponse> UpdateObject(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::me.jordanwood.proto.v1.statemanager.GenericResponse> CreateObject(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::me.jordanwood.proto.v1.statemanager.GenericResponse> RemoveObject(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::me.jordanwood.proto.v1.statemanager.AuthorityResponse> RetrieveAuthority(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::me.jordanwood.proto.v1.statemanager.EntityState> RetrieveState(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task StateStream(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::IServerStreamWriter<global::me.jordanwood.proto.v1.statemanager.EntityState> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SubscriptionStream(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::IServerStreamWriter<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for State</summary>
    public partial class StateClient : grpc::ClientBase<StateClient>
    {
      /// <summary>Creates a new client for State</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StateClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for State that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StateClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StateClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StateClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::me.jordanwood.proto.v1.statemanager.ConnectionRequest Connect(global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.ConnectionRequest Connect(global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Connect, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> ConnectAsync(global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> ConnectAsync(global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Connect, null, options, request);
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.PackedState FullLoad(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FullLoad(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.PackedState FullLoad(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FullLoad, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.PackedState> FullLoadAsync(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FullLoadAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.PackedState> FullLoadAsync(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FullLoad, null, options, request);
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.GenericResponse UpdateObject(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateObject(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.GenericResponse UpdateObject(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateObject, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.GenericResponse> UpdateObjectAsync(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateObjectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.GenericResponse> UpdateObjectAsync(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateObject, null, options, request);
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.GenericResponse CreateObject(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateObject(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.GenericResponse CreateObject(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateObject, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.GenericResponse> CreateObjectAsync(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateObjectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.GenericResponse> CreateObjectAsync(global::me.jordanwood.proto.v1.statemanager.EntityEditRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateObject, null, options, request);
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.GenericResponse RemoveObject(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveObject(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.GenericResponse RemoveObject(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RemoveObject, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.GenericResponse> RemoveObjectAsync(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RemoveObjectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.GenericResponse> RemoveObjectAsync(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RemoveObject, null, options, request);
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.AuthorityResponse RetrieveAuthority(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RetrieveAuthority(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.AuthorityResponse RetrieveAuthority(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RetrieveAuthority, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.AuthorityResponse> RetrieveAuthorityAsync(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RetrieveAuthorityAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.AuthorityResponse> RetrieveAuthorityAsync(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RetrieveAuthority, null, options, request);
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.EntityState RetrieveState(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RetrieveState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::me.jordanwood.proto.v1.statemanager.EntityState RetrieveState(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RetrieveState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.EntityState> RetrieveStateAsync(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RetrieveStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::me.jordanwood.proto.v1.statemanager.EntityState> RetrieveStateAsync(global::me.jordanwood.proto.v1.statemanager.EntityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RetrieveState, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::me.jordanwood.proto.v1.statemanager.EntityState> StateStream(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StateStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::me.jordanwood.proto.v1.statemanager.EntityState> StateStream(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StateStream, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> SubscriptionStream(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscriptionStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest> SubscriptionStream(global::me.jordanwood.proto.v1.statemanager.ConnectionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscriptionStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StateClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StateClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StateBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Connect, serviceImpl.Connect)
          .AddMethod(__Method_FullLoad, serviceImpl.FullLoad)
          .AddMethod(__Method_UpdateObject, serviceImpl.UpdateObject)
          .AddMethod(__Method_CreateObject, serviceImpl.CreateObject)
          .AddMethod(__Method_RemoveObject, serviceImpl.RemoveObject)
          .AddMethod(__Method_RetrieveAuthority, serviceImpl.RetrieveAuthority)
          .AddMethod(__Method_RetrieveState, serviceImpl.RetrieveState)
          .AddMethod(__Method_StateStream, serviceImpl.StateStream)
          .AddMethod(__Method_SubscriptionStream, serviceImpl.SubscriptionStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StateBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Connect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::me.jordanwood.proto.v1.statemanager.InitialConnectionRequest, global::me.jordanwood.proto.v1.statemanager.ConnectionRequest>(serviceImpl.Connect));
      serviceBinder.AddMethod(__Method_FullLoad, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.PackedState>(serviceImpl.FullLoad));
      serviceBinder.AddMethod(__Method_UpdateObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::me.jordanwood.proto.v1.statemanager.EntityEditRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse>(serviceImpl.UpdateObject));
      serviceBinder.AddMethod(__Method_CreateObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::me.jordanwood.proto.v1.statemanager.EntityEditRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse>(serviceImpl.CreateObject));
      serviceBinder.AddMethod(__Method_RemoveObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.GenericResponse>(serviceImpl.RemoveObject));
      serviceBinder.AddMethod(__Method_RetrieveAuthority, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.AuthorityResponse>(serviceImpl.RetrieveAuthority));
      serviceBinder.AddMethod(__Method_RetrieveState, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::me.jordanwood.proto.v1.statemanager.EntityRequest, global::me.jordanwood.proto.v1.statemanager.EntityState>(serviceImpl.RetrieveState));
      serviceBinder.AddMethod(__Method_StateStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.EntityState>(serviceImpl.StateStream));
      serviceBinder.AddMethod(__Method_SubscriptionStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::me.jordanwood.proto.v1.statemanager.ConnectionRequest, global::me.jordanwood.proto.v1.statemanager.ConnectionRequest>(serviceImpl.SubscriptionStream));
    }

  }
}
#endregion
